---
# asdaklsjdaklsjdaskldj
# 1. wazuh manager install
# 2. rotate passwords and log in register
# 3. wazuh agent install - does not have windows agent
# 4. graylog setup - change plans depending on distro, if graylog already installed
- name: Install Wazuh Manager
  hosts: manager
  become: yes
  roles:
    - manager
  tags:
    - logging
    - wazuh
    - manager
    - never

# - name: Install Wazuh Agents
#   hosts: linux
#   become: yes
#   roles: 
#     - agent
#   tags:
#     - logging
#     - wazuh
#     - agent
#     - never

- name: Install Wazuh Agents
  hosts: linux
  become: yes
  roles: 
    - ansible-wazuh-agent
  tags:
    - logging
    - wazuh
    - agent
    - never
  vars:
    wazuh_managers:
      - address: {{ manager_ip }}
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5

- name: Configure Graylog
  hosts: graylog
  become: yes
  vars_prompt:
    - name: root_password
      prompt: Enter graylog root password
      private: true
      encrypt: sha256_crypt
      confirm: true
      salt_size: 7

  roles:
    - graylog
  tags:
    - logging
    - graylog
    - never
