---
# By Justin Huang - jh6431@rit.edu
# Date: 09/13/2024
- name: Install Wazuh Manager
  hosts: manager
  become: yes
  tasks:
    - name: Download the Wazuh install script
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.9/wazuh-install.sh # download the official release of Wazuh from the source
        dest: /tmp/wazuh-install.sh
        mode: '0755'

    - name: Run the Wazuh install script
      ansible.builtin.command:
        cmd: bash /tmp/wazuh-install.sh -a -i -o # the -a option will install all of the server's components together, the -i option will ignore warnings, and the -o option will overwrite any previous installation in case there is one.
    
    - name: Install osquery
      ansible.builtin.package:
        name:
          - osquery
        state: latest
        
- name: Rotate Wazuh passwords
  hosts: manager
  become: yes
  tasks:
    - name: Download the Wazuh password changing utility
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.9/wazuh-passwords-tool.sh
        dest: /tmp/wazuh-passwords-tool.sh
        mode: '0755'
    
    - name: Run the Wazuh password changing script
      ansible.builtin.shell:
        cmd: bash /tmp/wazuh-passwords-tool.sh -a > /var/ossec/etc/wazuh-passwords.txt # the -a option will change passwords for all users, including API users
        # writes the output of the password rotation to a plaintext file, should be deleted or obscured after it is taken note of
       
- name: Reconfigure file permissions
  hosts: manager
  become: yes
  tasks:
    - name: Set ownership for ossec.log
      ansible.builtin.file:
        path: /var/ossec/logs/ossec.log
        owner: root
        group: wazuh
        mode: '0660'

- name: Set up agent groups
  hosts: manager
  become: yes
  tasks:
    - name: Add linux agent group
      command: /var/ossec/bin/agent_groups -a -g linux -q

    - name: Add windows agent group
      command: /var/ossec/bin/agent_groups -a -g windows -q

- name: Set up agent configurations
  hosts: manager
  become: yes
  tasks:
    - name: Configure kernel control commands
      copy:
        content: |
          insmod:
          rmmod:
          modprobe:
        dest: /var/ossec/etc/lists/kernel_control_commands

    - name: Copy osquery.conf
      copy:
        src: osquery.conf
        dest: /etc/osquery/osquery.conf

    - name: Copy centralized_agent.conf
      copy:
        src: centralized_agent.conf
        dest: /var/ossec/etc/shared/linux/agent.conf
        owner: wazuh
        group: wazuh
        mode: '0660'

    - name: Copy internal_options.conf
      copy:
        src: internal_options.conf
        dest: /var/ossec/etc/internal_options.conf
        owner: root
        group: wazuh
        mode: '0640'

    - name: Copy ossec.conf
      copy:
        src: ossec.conf
        dest: /var/ossec/etc/ossec.conf
        owner: root
        group: wazuh
        mode: '0660'

    - name: Copy linux_rules.xml
      copy:
        src: linux_rules.xml
        dest: /var/ossec/ruleset/rules/linux_rules.xml
        owner: root
        group: wazuh
        mode: '0660'

    - name: Copy windows_rules.xml
      copy:
        src: windows_rules.xml
        dest: /var/ossec/ruleset/rules/windows_rules.xml
        owner: root
        group: wazuh
        mode: '0660'