---
# Wazuh manager install and setup

- name: Install Wazuh Manager
  hosts: manager
  become: yes
  tasks:
    - name: Download the Wazuh install script
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.9/wazuh-install.sh
        dest: /tmp/wazuh-install.sh
        mode: '0755'

    - name: Run the Wazuh install script
      ansible.builtin.command:
        cmd: bash /tmp/wazuh-install.sh -a -i -o
      args:
        creates: /var/ossec
    
- name: Install osquery
  hosts: manager
  become: yes
  tasks:
    - name: Download osquery tarball
      ansible.builtin.get_url:
        url: https://pkg.osquery.io/linux/osquery-5.13.1_1.linux_x86_64.tar.gz
        dest: /tmp/osquery.tar.gz

    - name: Extract osquery tarball
      ansible.builtin.unarchive:
        src: /tmp/osquery.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move osquery binary to /usr/bin
      ansible.builtin.command:
        cmd: mv /opt/osquery-5.13.1_1.linux_x86_64/osquery* /usr/bin/
      args:
        removes: /usr/bin/osqueryd  # Remove the binary if it already exists
        warn: false

    - name: Set the correct permissions for osquery
      ansible.builtin.file:
        path: /usr/bin/osqueryd
        owner: root
        group: root
        mode: '0755'

    - name: Clean up the downloaded tarball
      ansible.builtin.file:
        path: /tmp/osquery.tar.gz
        state: absent

    - name: Start osquery daemon
      ansible.builtin.systemd:
        name: osqueryd
        state: started
        enabled: yes

- name: Rotate Wazuh passwords
  hosts: manager
  become: yes
  tasks:
    - name: Download the Wazuh password changing utility
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.9/wazuh-passwords-tool.sh
        dest: /tmp/wazuh-passwords-tool.sh
        mode: '0755'
    
    - name: Run the Wazuh password changing script
      ansible.builtin.shell:
        cmd: bash /tmp/wazuh-passwords-tool.sh -a > /var/ossec/etc/wazuh-passwords.txt

- name: Reconfigure file permissions
  hosts: manager
  become: yes
  tasks:
    - name: Set ownership for ossec.log
      ansible.builtin.file:
        path: /var/ossec/logs/ossec.log
        owner: root
        group: wazuh
        mode: '0660'

- name: Set up agent groups
  hosts: manager
  become: yes
  tasks:
    - name: Add linux agent group
      ansible.builtin.command: /var/ossec/bin/agent_groups -a -g linux -q

    - name: Add windows agent group
      ansible.builtin.command: /var/ossec/bin/agent_groups -a -g windows -q

- name: Set up agent configurations
  hosts: manager
  become: yes
  tasks:
    - name: Configure kernel control commands
      ansible.builtin.copy:
        content: |
          insmod:
          rmmod:
          modprobe:
        dest: /var/ossec/etc/lists/kernel_control_commands

    - name: Copy osquery.conf
      ansible.builtin.copy:
        src: osquery.conf
        dest: /etc/osquery/osquery.conf

    - name: Copy centralized_agent.conf
      ansible.builtin.copy:
        src: centralized_agent.conf
        dest: /var/ossec/etc/shared/linux/agent.conf
        owner: wazuh
        group: wazuh
        mode: '0660'

    - name: Copy internal_options.conf
      ansible.builtin.copy:
        src: internal_options.conf
        dest: /var/ossec/etc/internal_options.conf
        owner: root
        group: wazuh
        mode: '0640'

    - name: Copy ossec.conf
      ansible.builtin.copy:
        src: ossec.conf
        dest: /var/ossec/etc/ossec.conf
        owner: root
        group: wazuh
        mode: '0660'

    - name: Copy linux_rules.xml
      ansible.builtin.copy:
        src: linux_rules.xml
        dest: /var/ossec/ruleset/rules/linux_rules.xml
        owner: root
        group: wazuh
        mode: '0660'

    - name: Copy windows_rules.xml
      ansible.builtin.copy:
        src: windows_rules.xml
        dest: /var/ossec/ruleset/rules/windows_rules.xml
        owner: root
        group: wazuh
        mode: '0660'

- name: Set up Yara (manager)
  hosts: manager
  become: yes
  tasks:
    - name: Copy over decoder for Yara
      ansible.builtin.copy:
        src: decoders/yara_decoder.xml
        dest: /var/ossec/etc/decoders/yara-decoder.xml
        owner: wazuh
        group: wazuh
        mode: '0660'

- name: Install Wazuh agents
  hosts: linux
  become: yes
  tasks:
    - name: Download and import Wazuh GPG key
      ansible.builtin.command: 
        cmd: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import"
      args:
        warn: false
    
    - name: Set permissions for the Wazuh GPG key
      ansible.builtin.file:
        path: /usr/share/keyrings/wazuh.gpg
        mode: '0644'
    
    - name: Add Wazuh repository to sources list
      ansible.builtin.command: 
        cmd: echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
    
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install Wazuh agent using environment variable
      ansible.builtin.shell: 
        cmd: WAZUH_MANAGER="{{ hostvars['manager'][0] }}" apt-get install -y wazuh-agent

    - name: Download osquery tarball
      ansible.builtin.get_url:
        url: https://pkg.osquery.io/linux/osquery-5.13.1_1.linux_x86_64.tar.gz
        dest: /tmp/osquery.tar.gz

    - name: Extract osquery tarball
      ansible.builtin.unarchive:
        src: /tmp/osquery.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move osquery binary to /usr/bin
      ansible.builtin.command:
        cmd: mv /opt/osquery-5.13.1_1.linux_x86_64/osquery* /usr/bin/
      args:
        removes: /usr/bin/osqueryd  # Remove the binary if it already exists
        warn: false

    - name: Set the correct permissions for osquery
      ansible.builtin.file:
        path: /usr/bin/osqueryd
        owner: root
        group: root
        mode: '0755'

    - name: Clean up the downloaded tarball
      ansible.builtin.file:
        path: /tmp/osquery.tar.gz
        state: absent

    - name: Start osquery daemon
      ansible.builtin.systemd:
        name: osqueryd
        state: started
        enabled: yes

- name: Install YARA and configure YARA rules
  hosts: linux
  become: yes
  tasks:
    - name: Install YARA and git
      ansible.builtin.package:
        name: 
          - yara
          - git
        state: present

    - name: Create /opt/yara/rules directory
      ansible.builtin.file:
        path: /opt/yara/rules
        state: directory
        mode: '0755'

    - name: Clone protections-artifacts repository
      ansible.builtin.git:
        repo: https://github.com/elastic/protections-artifacts
        dest: /opt/yara/rules/protections-artifacts
        force: yes

    - name: Compile YARA rules
      ansible.builtin.command: 
        cmd: yarac Linux* Multi* /opt/yara/rules/compiled.linux
      args:
        chdir: /opt/yara/rules/protections-artifacts/yara/rules

    - name: Copy over YARA active response script
      ansible.builtin.copy: 
        src: yara.sh
        dest: /var/ossec/active-response/bin/yara.sh
        owner: root
        group: wazuh 
        mode: '0750'

- name: Enable and restart wazuh-agent service
  hosts: linux
  become: yes
  tasks:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started
