---
# Wazuh manager install and setup

- name: Install Wazuh Manager
  hosts: manager
  become: yes
  tasks:
    - name: Download the Wazuh install script
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.9/wazuh-install.sh
        dest: /tmp/wazuh-install.sh
        mode: '0755'

    - name: Run the Wazuh install script
      ansible.builtin.command:
        cmd: bash /tmp/wazuh-install.sh -a -i -o
      args:
        creates: /var/ossec

# - name: Install osquery
#   hosts: all
#   become: yes
#   tasks:
#     - name: Create keyrings directory
#       ansible.builtin.file:
#         path: /etc/apt/keyrings
#         state: directory

#     - name: Download osquery GPG key
#       ansible.builtin.command:
#         cmd: curl -L https://pkg.osquery.io/deb/pubkey.gpg | tee /etc/apt/keyrings/osquery.asc


#     - name: Add osquery repository
#       ansible.builtin.command:
#         cmd: echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/osquery.asc] https://pkg.osquery.io/deb deb main" | tee -a /etc/apt/sources.list.d/osquery.list

#     - name: Update apt package index
#       ansible.builtin.apt:
#         update_cache: yes

#     - name: Install osquery
#       ansible.builtin.apt:
#         name: osquery
#         state: present

- name: Rotate Wazuh passwords
  hosts: manager
  become: yes
  tasks:
    - name: Download the Wazuh password changing utility
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.9/wazuh-passwords-tool.sh
        dest: /tmp/wazuh-passwords-tool.sh
        mode: '0755'
    
    - name: Run the Wazuh password changing script
      ansible.builtin.shell:
        cmd: bash /tmp/wazuh-passwords-tool.sh -a > /var/ossec/etc/wazuh-passwords.txt
      args:
        creates: /var/ossec/etc/wazuh-passwords.txt

- name: Reconfigure file permissions
  hosts: manager
  become: yes
  tasks:
    - name: Set ownership for ossec.log
      ansible.builtin.file:
        path: /var/ossec/logs/ossec.log
        owner: root
        group: wazuh
        mode: '0660'

- name: Set up agent groups
  hosts: manager
  become: yes
  tasks:
    - name: Add linux agent group
      ansible.builtin.command: /var/ossec/bin/agent_groups -a -g linux -q

    - name: Add windows agent group
      ansible.builtin.command: /var/ossec/bin/agent_groups -a -g windows -q

- name: Set up agent configurations
  hosts: manager
  become: yes
  tasks:
    - name: Configure kernel control commands
      ansible.builtin.copy:
        content: |
          insmod:
          rmmod:
          modprobe:
        dest: /var/ossec/etc/lists/kernel_control_commands

    # - name: Copy osquery.conf
    #   ansible.builtin.copy:
    #     src: osquery.conf
    #     dest: /etc/osquery/osquery.conf

    - name: Copy centralized_agent.conf
      ansible.builtin.copy:
        src: centralized_agent.conf
        dest: /var/ossec/etc/shared/linux/agent.conf
        owner: wazuh
        group: wazuh
        mode: '0660'

    - name: Copy internal_options.conf
      ansible.builtin.copy:
        src: internal_options.conf
        dest: /var/ossec/etc/internal_options.conf
        owner: root
        group: wazuh
        mode: '0640'

    - name: Copy ossec.conf
      ansible.builtin.copy:
        src: ossec.conf
        dest: /var/ossec/etc/ossec.conf
        owner: root
        group: wazuh
        mode: '0660'

    - name: Copy linux_rules.xml
      ansible.builtin.copy:
        src: linux_rules.xml
        dest: /var/ossec/ruleset/rules/linux_rules.xml
        owner: root
        group: wazuh
        mode: '0660'

    - name: Copy windows_rules.xml
      ansible.builtin.copy:
        src: windows_rules.xml
        dest: /var/ossec/ruleset/rules/windows_rules.xml
        owner: root
        group: wazuh
        mode: '0660'

- name: Set up Yara (manager)
  hosts: manager
  become: yes
  tasks:
    - name: Copy over decoder for Yara
      ansible.builtin.copy:
        src: decoders/yara_decoder.xml
        dest: /var/ossec/etc/decoders/yara-decoder.xml
        owner: wazuh
        group: wazuh
        mode: '0660'

- name: Install Linux Wazuh agents
  hosts: linux
  become: yes
  tasks:
    - name: copy over wazuh binary
      ansible.builtin.copy:
        src: binaries/wazuh-agent_4.7.2-1_amd64_debian.deb
        dest: /tmp/wazuh-agent_4.7.2-1_amd64_debian.deb
    
    - name: Install Wazuh agent from binary
      ansible.builtin.apt:
        deb: /tmp/wazuh-agent_4.7.2-1_amd64_debian.deb
        state: present
        
    # - name: Install curl
    #   ansible.builtin.package:
    #     name: curl
    #     state: present
        
    # - name: Download and import Wazuh GPG key
    #   ansible.builtin.command: 
    #     cmd: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import"
    
    # - name: Set permissions for the Wazuh GPG key
    #   ansible.builtin.file:
    #     path: /usr/share/keyrings/wazuh.gpg
    #     mode: '0644'
    
    # - name: Add Wazuh repository to sources list
    #   ansible.builtin.command: 
    #     cmd: echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
    
    # - name: Update apt package index
    #   ansible.builtin.apt:
    #     update_cache: yes
    
    # - name: Install Wazuh agent using environment variable
    #   ansible.builtin.shell: 
    #     cmd: WAZUH_MANAGER="{{ MANAGER_IP }}" apt-get install -y wazuh-agent 

- name: Install YARA and configure YARA rules
  hosts: linux
  become: yes
  tasks:
    - name: Install YARA and git
      ansible.builtin.package:
        name: 
          - yara
          - git
        state: present

    - name: Create /opt/yara/rules directory
      ansible.builtin.file:
        path: /opt/yara/rules
        state: directory
        mode: '0755'

    - name: Copy over compiled YARA rules
      ansible.builtin.copy:
        src: compiled.linux
        dest: /opt/yara/rules/compiled.linux
        owner: root
        group: wazuh
        mode: '0660'

    - name: Copy over YARA active response script
      ansible.builtin.copy: 
        src: yara.sh
        dest: /var/ossec/active-response/bin/yara.sh
        owner: root
        group: wazuh 
        mode: '0750'

- name: Enable and restart wazuh-agent service
  hosts: linux
  become: yes
  tasks:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started
