---
# Wazuh manager install and setup
- name: Copy the Wazuh install script
  ansible.builtin.copy:
    src: wazuh-install.sh 
    dest: /tmp/wazuh-install.sh
    mode: '0755'

- name: Set manager IP in script
  ansible.builtin.replace:
    path: /tmp/wazuh-install.sh
    regexp: "MANAGERIPHERE"
    replace: "{{ manager_ip }}"

- name: Run the Wazuh install script
  ansible.builtin.command:
    cmd: bash /tmp/wazuh-install.sh -a -i -o
  args:
    creates: /var/ossec
    
- name: Create the keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download the osquery GPG key
  ansible.builtin.get_url:
    url: https://pkg.osquery.io/deb/pubkey.gpg
    dest: /etc/apt/keyrings/osquery.asc
    mode: '0644'

- name: Add the osquery repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/osquery.asc] https://pkg.osquery.io/deb deb main"
    state: present

- name: Install osquery
  ansible.builtin.apt:
    name: osquery
    state: present
    update_cache: true

- name: Copy the Wazuh password changing utility
  ansible.builtin.copy:
    src: wazuh-passwords-tool.sh 
    dest: /tmp/wazuh-passwords-tool.sh
    owner: wazuh
    group: wazuh
    mode: '0755'

# - name: Ensure indexer backup directory has the proper permissions
#   ansible.builtin.file:
#     path: /etc/wazuh-indexer/backup
#     owner: wazuh-indexer
#     group: wazuh-indexer
#     mode: '0750'

- name: Change all wazuh passwords
  ansible.builtin.shell:
    cmd: bash /tmp/wazuh-passwords-tool.sh -a > /var/ossec/etc/wazuh-passwords.txt
  args:
    creates: /var/ossec/etc/wazuh-passwords.txt
        
- name: Change the wazuh admin user password
  ansible.builtin.shell:
    cmd: bash /tmp/wazuh-passwords-tool.sh -u admin -p "{{ wazuh_password }}" -v
  args:
    creates: /var/ossec/etc/wazuh-passwords.txt

- name: Extract the Wazuh API password from the tar file
  ansible.builtin.shell: |
    tar -axf /tmp/wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O | grep -P "'wazuh'" -A 1 | grep -Po "(?<=api_password: ')[^']+"
  register: wazuh_api_password
  changed_when: false

- name: Debug extracted API password
  ansible.builtin.debug:
    msg: "API password: {{ wazuh_api_password.stdout }}"

- name: Save API password to a fact
  ansible.builtin.set_fact:
    wazuh_api_password: "{{ wazuh_api_password.stdout }}"

- name: Authenticate and retrieve the token
  ansible.builtin.command:
    cmd: >
        curl -u wazuh:{{ wazuh_api_password }} -k -X POST "https://127.0.0.1:55000/security/user/authenticate"
  register: auth_response
  changed_when: false 

- name: Extract the token from the response
  ansible.builtin.set_fact:
    wazuh_token: "{{ auth_response.stdout | from_json | json_query('data.token') }}"

- name: Debug the token
  ansible.builtin.debug:
    msg: "Wazuh API token: {{ wazuh_token }}"

- name: Send API request to add Graylog user
  ansible.builtin.command:
    cmd: >
      curl -X POST https://127.0.0.1:55000/security/users
      -H "Authorization: Bearer {{ wazuh_token }}"
      -H "Content-Type: application/json"
      -d '{"password": "{{ wazuh_graylog_password }}", "username": "graylog"}'
      -k
  register: create_user_response

- name: Debug the response from user creation
  ansible.builtin.debug:
    msg: "Response from user creation: {{ create_user_response }}"

- name: Set ownership for ossec.log
  ansible.builtin.file:
    path: /var/ossec/logs/ossec.log
    owner: root
    group: wazuh
    mode: '0660'

- name: Add linux agent group
  ansible.builtin.command: /var/ossec/bin/agent_groups -a -g linux -q

- name: Add windows agent group
  ansible.builtin.command: /var/ossec/bin/agent_groups -a -g windows -q

- name: Configure kernel control commands
  ansible.builtin.copy:
    content: |
      insmod:
      rmmod:
      modprobe:
    dest: /var/ossec/etc/lists/kernel_control_commands

- name: Copy osquery.conf
  ansible.builtin.copy:
    src: osquery.conf
    dest: /etc/osquery/osquery.conf

- name: Memory locking
  ansible.builtin.lineinfile:
    path: /etc/wazuh-indexer/opensearch.yml
    line: "bootstrap.memory_lock: true"
    state: present

- name: Memory locking
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/wazuh-indexer.service
    line: LimitMEMLOCK=infinity
    state: present
    insertafter: '^\[Service\]$'
  
- name: Fetch wazuh indexer cert 
  ansible.builtin.fetch:
    src: /etc/wazuh-indexer/certs/wazuh-indexer.pem
    dest: /opt/wazuh-indexer.pem
    flat: yes

- name: Copy Linux agent configs
  ansible.builtin.copy:
    src: agent_linux.conf
    dest: /var/ossec/etc/shared/linux/agent.conf
    owner: wazuh
    group: wazuh
    mode: '0660'

- name: Copy Windows agent configs
  ansible.builtin.copy:
    src: agent_windows.conf
    dest: /var/ossec/etc/shared/windows/agent.conf
    owner: wazuh
    group: wazuh
    mode: '0660'

- name: Copy internal_options.conf
  ansible.builtin.copy:
    src: internal_options.conf
    dest: /var/ossec/etc/internal_options.conf
    owner: root
    group: wazuh
    mode: '0640'

- name: Copy ossec.conf
  ansible.builtin.copy:
    src: ossec.conf
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: wazuh
    mode: '0660'

- name: Add subnet info to ossec.conf
  ansible.builtin.replace:
    path: /var/ossec/etc/ossec.conf
    regexp: "SUBNETHERE"
    replace: "{{ subnet }}"

- name: Add manager IP to ossec.conf
  ansible.builtin.replace:
    path: /var/ossec/etc/ossec.conf
    regexp: "MANAGERIPHERE"
    replace: "{{ manager_ip }}"

- name: Copy linux_rules.xml
  ansible.builtin.copy:
    src: linux_rules.xml
    dest: /var/ossec/etc/rules/linux_rules.xml
    owner: root
    group: wazuh
    mode: '0660'

- name: Copy windows_rules.xml
  ansible.builtin.copy:
    src: windows_rules.xml
    dest: /var/ossec/etc/rules/windows_rules.xml
    owner: root
    group: wazuh
    mode: '0660'

- name: Copy over decoders
  ansible.builtin.copy:
    src: decoders/
    dest: /var/ossec/etc/decoders/
    owner: wazuh
    group: wazuh
    mode: '0660'

- name: Find all files in the decoders directory
  ansible.builtin.find:
    paths: /var/ossec/etc/decoders/
    recurse: yes
  register: decoders_files

- name: Set correct permissions for all decoder files
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: wazuh
    group: wazuh
    mode: '0660'
  loop: "{{ decoders_files.files }}"

- name: Set up fluentbit
  ansible.builtin.copy:
    src: fluentbit.sh
    dest: /tmp/fluentbitinstall.sh
    mode: 0755
  
- name: Run the fluentbit install script
  ansible.builtin.command:
    cmd: bash /tmp/fluentbitinstall.sh 

- name: Install fluentbit configuration 
  template:
    src: fluentbit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    mode: 0644

- name: Enable and restart Wazuh Indexer
  systemd:
    name: wazuh-indexer.service
    enabled: true
    daemon_reload: true
    state: restarted

- name: Enable and restart Wazuh Manager
  systemd:
    name: wazuh-manager.service
    enabled: true
    state: restarted

- name: Enable and restart Wazuh Dashboard
  systemd:
    name: wazuh-dashboard.service
    enabled: true
    state: restarted